name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=24.5.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cryptography=42.0.5
  - distro=1.9.0
  - expat=2.6.2
  - fmt=9.1.0
  - frozendict=2.4.2
  - gflags=2.2.2
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.7.1
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libjemalloc=5.3.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - menuinst=2.1.1
  - ncurses=6.4
  - openssl=3.3.1
  - packaging=23.2
  - pcre2=10.42
  - pip=24.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.2
  - python-rocksdb=0.7.0
  - python_abi=3.12
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - rocksdb=6.29.5
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - snappy=1.1.10
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.66.4
  - truststore=0.8.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - blinker==1.8.2
      - botocore==1.34.153
      - click==8.1.7
      - colorama==0.4.6
      - datasets==2.20.0
      - dill==0.3.8
      - django==5.0.7
      - docutils==0.16
      - duckdb==1.0.0
      - elastic-transport==8.13.1
      - elasticsearch==8.14.0
      - faiss-cpu==1.8.0.post1
      - filelock==3.15.4
      - flask==3.0.3
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - huggingface-hub==0.24.1
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.2
      - prometheus-client==0.20.0
      - protobuf==5.27.2
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - redis==5.0.7
      - regex==2024.5.15
      - rsa==4.7.2
      - s3transfer==0.10.2
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - six==1.16.0
      - sqlparse==0.5.1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - transformers==4.43.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - werkzeug==3.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
